%YAML:1.0

#####
##### Definitions
#####
# Input parameters are defined in Parameters.hpp
# Rotations are quaternions specified as: x,y,z,w (the same as ROS TF notation)


#####
##### Notes on this specific configuration file
#####
# Current camera settings for the robot.
# rosrun tf tf_echo base realsense_d435_forward_color_optical_frame


#####
##### Camera Parameters
##### works with anymal_2019-05-10-10-38-35.bag
cameras:
    - {
      depth_source_type : "stereo",
      image_dimensions: [640,480],
      focal_length:     [462.1379699707031, 320.0], # default from camera info, David uses different
      focal_point:      [462.1379699707031, 240.0],
      # distortion_s:    0, # used by David but not used here
      distortion_k1:   0.0,
      distortion_k2:   0.0,
      distortion_k3:   0.0, # not used by David
      distortion_p1:   0.0,
      distortion_p2:   0.0,

      stereo_baseline: 0.05, # positive, as for David. internally fovis used -0.05


      # same configuration tested for VILENS paper (ICRA 2019)
#      B_r_BC: [0.371, 0.018, 0.162],
#      B_q_BC: [-0.5418, 0.5552, -0.4516, 0.4407] 
      B_r_BC: [0.500, 0.015, 0.100],
      B_q_BC: [0.00, 0.00, 0.00, 1.00] 
      
      # previous configuration manually found by M. Fallon
      # B_r_BC: [0.371, 0.018, 0.162]
      # B_q_BC: [0.549529, -0.445107, 0.445016, -0.549417] # x y z w

      #B_r_BC: [0.383, 0.015, 0.143], # David's values
      #B_q_BC: [0.546, -0.546, 0.449, -0.449], # David's values
      }
